### ISSUE TITLE
Is it possible to add a search icon to the left of search input?

### ISSUE THREAD

**Issue by TarekMansour** [Blazored/Typeahead#216]
I'm using `Blazored.Typeahead  4.4.0` package for an auto complete search bar and I want to add a search icon on the left of typeahead, is it possible?

**Comment by chrissainty** [comment]
We don't have anything built into the component to do this for you. But you could achieve this with custom markup and CSS. Something like this:

```razor
<div class="my-wrapper">
    <img ... />
    <BlazoredTypeahead ... />
</div>
```

```css
.my-wrapper {
    display: flex;
    flex-direction: row;
    border: 1px solid #f5f5f5
}

.my-wrapper > .blazored-typeahead {
    border: none;
}
```

I've not tested this but it should get you going.
