### ISSUE TITLE
Enable Results list to be wider than Input box

### ISSUE THREAD

**Issue by rgamage** [Blazored/Typeahead#88]
Often the results template has more information (e.g. part number + part description) than the input box (e.g. part number), which means you would like the results drop-down to be wider than the input box... I couldn't find a way to do this - is it possible as the control is written?

**Comment by chrissainty** [comment]
Yes, it's possible to change the width. You can override the `.blazored-typeahead__results` CSS class, for example:
```css
.blazored-typeahead__results {
    width: 110%;
}
```
or

```css
.blazored-typeahead__results {
    width: 100px;
}
```
